noun1 = input ("Noun >> ")
place1 = input ("Place >> ")
adj1 = input ("Adjective >> ")
noun2 = input ("Noun >> ")
adv1 = input ("Adverb >> ")
verb1 = input ("Verb >> ")
adv2 = input ("Adverb >> ")
verb2 = input ("Verb >> ")
verb3 = input ("Verb >> ")
favstore = input ("Favorite Store >> ")
adv3 = input ("Adverb >> ")
verb4 = input ("Verb >> ")
favicecream = input ("Favorite icecream flavor >> ")

print ("You wake up on a/an", noun1, ' in the middle of ', place1, '. To your right is a/an ', adj1, noun2,)
print ("who is ", adv1, verb1, "towards you. You ", adv2, verb2, " away, but you are still being followed.")
print ("You decide to ", verb3, "when you see a/an", favstore, "having a special deal on icecream")
print ("You stop what you're doing and ", adv3, verb4, ' to find icecream. The ', noun2, ' is still ',)
print (verb1, ' at you, but its ok because you have your favorite flavor of icecream, ', favicecream, '.')
